config_version: 2
global:  # Common settings for all suites
  settings:  # Settings
    project_name: PetClinic  # Project name
  processing: # Processing config
    min_severity_filter: # Filters findings below minimal severity level
      severity: Info # Minimal severity level to report, one of: Critical, High, Medium, Low, Info
    false_positive:
      galloper: galloper-url
      project_id: 1
      token: galloper-token
    quality_gate:
      thresholds:
        Critical: 1
        High: 5
  reporters: # Reporters config
    html: # HTML reporter
      file: /tmp/reports/report.html
    junit:
      file: /tmp/reports/report.xml
    galloper:
      url: galloper-url
      project_id: 1
      token: galloper-token
suites: # Test suites
  sca:  # Example test suite
    settings:  # Settings
      project_description: PetClinicCI # Project description (or application name)
      environment_name: master # Environment under testing (branch/module for SAST)
      testing_type: SAST # DAST or SAST
      scan_type: full # full, incremental or other scan description (e.g.: qualys, authorized, etc)
      build_id: '1' # Build number (or some other identifier)
      sast: # Settings common to all SAST scanners
        max_concurrent_scanners: 4  # Maximum number of concurrent SAST scanners
    scanners:
      sast:
        java:
          code: /code
          composition_analysis: True
        gitleaks:
          code: /code
          use_custom_rules: true
          squash_commits: true